# Generated by Django 4.1 on 2022-08-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.FloatField()),
                ('contactNo', models.CharField(max_length=100)),
                ('workchoice', models.CharField(choices=[('work from home', 'work from home'), ('work from office', 'work from office')], max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
