# Generated by Django 4.1 on 2022-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isMarried',
            field=models.BooleanField(null=True),
        ),
    ]
