# Generated by Django 4.1 on 2022-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employee_ismarried'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
